### DISCUSSION TITLE
The fictioneer 5.24 theme is experiencing CSS errors on WordPress 6.6.2,

### DISCUSSION THREAD

**Discussion by xruozhen** [Tetrakern/fictioneer#47] [General]
The fictioneer 5.24 theme is experiencing CSS errors on WordPress 6.6.2, including issues at the top and bottom of the pages where checkboxes appear, and an inability to adjust font sizes on the Chapter pages. More details can be seen at: https://luxunlib.com/. I am wondering if there will be an update to address these issues. Thank you!

**Comment by Tetrakern** [comment]
This is not an error of the theme but appears to be caused by one of your plugins, something with forms I guess from the interfering CSS declarations coming from a `form.min.css`. It uses some extremely generic selectors. Similar issue with the chapters, some `common.min.css` has a CSS declaration that sets every paragraph to 13px font-size, breaking the style.

I cannot tell what is causing this, but it is not the theme. Applying CSS to element-type selectors is not a great idea as these should be reserved to the theme (case in point). And `.card` is super generic, bold to assume that can just be used too. Have you recently installed some new plugins?

**Edit:** Are you using Spectra or another block editor plugin? Fictioneer is not a block theme and not particularly compatible with such plugins.

**Edit 2:** I suppose you could try to fix the issues with custom CSS, but that will be a lot of work and probably never be perfect. For example:

```css
[hidden] {
  display: none !important;
}

.content-section p {
  font-size: inherit;
}

:is(.card-list, .grid-columns) .card {
  background: none;
  padding: 0;
  margin-top: 0;
  border: 0;
  min-width: auto;
}
```

This should remove the most obvious errors, but there is a lot wrong elsewhere. I recommend not using the plugin.

<img width="488" alt="image" src="https://github.com/user-attachments/assets/986cfab8-25ef-4e65-b680-c0a2594bdd59">

<img width="489" alt="image" src="https://github.com/user-attachments/assets/f4443c87-bbf0-4cc2-8d8f-bc6590854d0a">

<img width="490" alt="image" src="https://github.com/user-attachments/assets/666afbc9-7a58-4f64-a2c6-32526c2d16bc">
